title: "<p style='text-align: center; font-weight: bold; font-size: 28px; color: black; margin-bottom: 10px;'>Shishir Khanal</p>"
logo: "/assets/img/4.jfif"
description: >
  <p align="center">
    <a href="https://jp.linkedin.com/in/er-shishir-khanal-26b125139" 
    style="display: inline-block; padding: 6px 15px; font-size: 14px; 
    font-weight: bold; color: white; background-color: #0073b1; 
    text-decoration: none; border-radius: 4px;">
      Connect on LinkedIn
    </a>
  </p>

  <div style="color: black; text-align: center; font-weight: bold; background-color: lightblue; padding: 10px; border-radius: 5px;">
    Engineer | AI | ML | Deep Learning | NLP | Gen AI | LLM | Python | Mechanical Engineering  
  </div>

  <br>

  <div style="text-align: center; background-color: lightgray; padding: 10px; border-radius: 5px;">
    <span style="color: darkblue; font-style: italic;">
      “Education is not the learning of facts, but the training of the mind to think.”
    </span>
    <br>
    <span style="color: darkblack;">― Albert Einstein</span>
  </div>










