title: "<div style='text-align: center;'><p style='color: blue; font-weight: bold;'>Shishir Khanal</p></div>"
logo: /assets/img/think_about_code.jpg
description: <p align="center">
  <a href="https://jp.linkedin.com/in/er-shishir-khanal-26b125139/">LinkedIn</a>
  <br> 
  <br>
  <div style="color: black; text-align: center; font-weight: bold;">
  Design(2D/3D),Simulation,Analysis & Additive Manufacturing (Industrial Robot/Mechanical Device & Production Automation Research and Development) Engineer at Japan,Tokyo 
  <br>
  </p>
  </div>
