title: "<div style='text-align: center;'><p style='color: lightgray; font-weight: bold;'>Shishir Khanal</p></div>"
logo: /assets/img/think_about_code.jpg
description: |
  <p align="center">
    <a href="https://jp.linkedin.com/in/er-shishir-khanal-26b125139" style="font-size: 18px; color: blue; text-decoration: underline;">LinkedIn</a>
  </p>
  <div style="color: black; text-align: center; font-weight: bold; background-color: lightblue;">
    Design(2D/3D), Simulation, Analysis & Additive Manufacturing (Industrial Robot/Mechanical Device & Production Automation Research and Development) Engineer at Japan, Tokyo
  </div>

