title: "Shishir Khanal"
logo: "/assets/img/001.jpg"
description: >
  <p align="center">
    <a href="https://jp.linkedin.com/in/er-shishir-khanal-26b125139" 
    style="font-size: 16px; color: blue; text-decoration: underline;">
      Connect on LinkedIn
    </a>
  </p>
  <div style="color: black; text-align: center; font-weight: bold; background-color: lightblue; padding: 10px;">
    AI Engineer | ML | Deep Learning | NLP | Gen AI | LLM | Python | Mechanical Engineering  
    <br><br>
    
    <div style="background-color: darkgray; padding: 2px;">
      <hr style="border: none; height: 2px; background-color: white; width: 80%;">
    </div>
    
    <br><br>
    <span style="color: darkblue; font-style: italic;">
      “Education is not the learning of facts, but the training of the mind to think.”
    </span>
    <br>
    <span style="color: darkred;">― Albert Einstein</span>
  </div>







