title: "<div style='text-align: center;'><p style='color: blue; font-weight: bold;'>Shishir Khanal</p></div>"
logo: /assets/img/think_about_code.jpg
description: |
  <p align="center">
    <a href="https://jp.linkedin.com/in/er-shishir-khanal-26b125139" style="font-size: 18px; color: blue; text-decoration: underline;">LinkedIn</a>
  </p>
  <div id="description" style="color: black; text-align: center; font-weight: bold;"></div>
<script>
  // Function to animate text one letter at a time
  function animateText() {
    const descriptionElement = document.getElementById("description");
    const text = "Design(2D/3D), Simulation, Analysis & Additive Manufacturing (Industrial Robot/Mechanical Device & Production Automation Research and Development) Engineer at Japan, Tokyo";
    let index = 0;

    function addLetter() {
      if (index < text.length) {
        descriptionElement.innerHTML += text.charAt(index);
        index++;
        setTimeout(addLetter, 50); // Adjust the duration between letters (in milliseconds)
      }
    }

    addLetter();
  }

  // Call the animation function when the page is loaded
  window.onload = animateText;
</script>


