title: Shishir Khanal
logo: /assets/img/think_about_code.jpg
description: Design(2D/3D),Simulation,Analysis & Additive Manufacturing (Industrial Robot/Mechanical Device & Production Automation Research and Development) Engineer at Japan,Tokyo
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
