title: "<div style='text-align: center;'><p style='color: blue; font-weight: bold;' id='name'>Shishir Khanal</p></div>"
logo: /assets/img/think_about_code.jpg
description: |
  <p align="center">
    <a href="https://jp.linkedin.com/in/er-shishir-khanal-26b125139" style="font-size: 18px; color: blue; text-decoration: underline;">LinkedIn</a>
  </p>
  <div style="color: black; text-align: center; font-weight: bold;">
    Design(2D/3D), Simulation, Analysis & Additive Manufacturing (Industrial Robot/Mechanical Device & Production Automation Research and Development) Engineer at Japan, Tokyo
  </div>

<style>
  @keyframes fadeInScaleUp {
    from {
      opacity: 0;
      transform: scale(0);
    }
    to {
      opacity: 1;
      transform: scale(1);
    }
  }

  #name {
    animation: fadeInScaleUp 1.5s ease-in-out forwards;
  }
</style>

