title: "<div style='text-align: center;'><p style='color: black; font-weight: bold;'>Shishir Khanal</p></div>"
logo: /assets/img/001.jpg
description: |
  <p align="center">
    <a href="https://jp.linkedin.com/in/er-shishir-khanal-26b125139" style="font-size: 16px; color: blue; text-decoration: underline;">Connect on LinkedIn</a>
  </p>
  <div style="color: black; text-align: center; font-weight: bold; background-color: lightblue;">
    Researcher/Engineer
  </div>
  <p align="center" style="margin-top: 20px;">
    <a href="mailto:shishir.khanal40@gmail.com" style="display: inline-block; padding: 10px 20px; font-size: 16px; color: white; background-color: blue; text-decoration: none; border-radius: 5px; font-weight: bold; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);">
      Message me
    </a>
  </p>
  <form action="https://formspree.io/f/xpzvvwpw" method="POST" style="text-align: center; margin-top: 20px;">
    <label for="email" style="font-weight: bold;">Your Email:</label><br>
    <input type="email" id="email" name="email" required style="margin-top: 10px; padding: 10px; width: 80%; max-width: 300px; border: 1px solid #ccc; border-radius: 5px;"><br><br>
    <label for="message" style="font-weight: bold;">Your Message:</label><br>
    <textarea id="message" name="message" rows="4" required style="margin-top: 10px; padding: 10px; width: 80%; max-width: 300px; border: 1px solid #ccc; border-radius: 5px;"></textarea><br><br>
    <button type="submit" style="padding: 10px 20px; font-size: 16px; color: white; background-color: blue; border: none; border-radius: 5px; font-weight: bold; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);">
      Send Message
    </button>
  </form>


