title: "<div style='text-align: center;'><p style='color: black; font-weight: bold;'>Shishir Khanal</p></div>"
logo: /assets/img/001.jpg
description: |
  <p align="center">
    <a href="https://jp.linkedin.com/in/er-shishir-khanal-26b125139" style="font-size: 16px; color: blue; text-decoration: underline;">Connect on LinkedIn</a>
  </p>
  <div style="color: black; text-align: center; font-weight: bold; background-color: lightblue;">
    Researcher/Engineer
  </div>
  <p align="center">
    <a href="mailto:shishir.khanal40@gmail.com" class="message-button" style="display: inline-block; padding: 10px 20px; font-size: 16px; color: white; background-color: #007bff; border: none; border-radius: 5px; text-align: center; text-decoration: none; cursor: pointer;">Message Me</a>
  </p>

